spring:
  application:
    name: "account-manager-pet"
  datasource:
    url: jdbc:mysql://localhost:3306/account_manager
    username: root
    password: Ebaldremal228
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: user